### ISSUE TITLE
Database error when scheduling a job

### ISSUE THREAD

**Issue by valexopoulos** [qlack/QLACK-Java#14]
Following the example at https://github.com/qlack/QLACK-Java/tree/master/QLACK-Fuse/qlack-fuse-scheduler and specifically the **Schedule jobs on Application start** for LoggerJob class and while connected to the H2 database I get the following error:

`java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at com.example.demo.DemoApplication.main(DemoApplication.java:27) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.3.1.RELEASE.jar:2.3.1.RELEASE]
Caused by: com.eurodyn.qlack.fuse.scheduler.exception.QSchedulerException: org.quartz.JobPersistenceException: Couldn't store job: Value too long for column "IS_DURABLE VARCHAR(1)": "'TRUE' (4)"; SQL statement:
INSERT INTO sch_JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP, DESCRIPTION, JOB_CLASS_NAME, IS_DURABLE, IS_NONCONCURRENT, IS_UPDATE_DATA, REQUESTS_RECOVERY, JOB_DATA)  VALUES('quartzScheduler', ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-200] [See nested exception: org.h2.jdbc.JdbcSQLDataException: Value too long for column "IS_DURABLE VARCHAR(1)": "'TRUE' (4)"; SQL statement:
INSERT INTO sch_JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP, DESCRIPTION, JOB_CLASS_NAME, IS_DURABLE, IS_NONCONCURRENT, IS_UPDATE_DATA, REQUESTS_RECOVERY, JOB_DATA)  VALUES('quartzScheduler', ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-200]]
	at com.eurodyn.qlack.fuse.scheduler.service.SchedulerService.scheduleJob(SchedulerService.java:260) ~[qlack-fuse-scheduler-3.2.8.jar:na]
	at com.eurodyn.qlack.fuse.scheduler.service.SchedulerService$$FastClassBySpringCGLIB$$112bf724.invoke(<generated>) ~[qlack-fuse-scheduler-3.2.8.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at com.eurodyn.qlack.fuse.scheduler.service.SchedulerService$$EnhancerBySpringCGLIB$$e405f5f8.scheduleJob(<generated>) ~[qlack-fuse-scheduler-3.2.8.jar:na]
	at com.example.demo.DemoApplication.run(DemoApplication.java:36) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	... 8 common frames omitted`

Please advise. Thank you very much.

*Please find also attached the demo project.
[demo.zip](https://github.com/qlack/QLACK-Java/files/4864379/demo.zip)

**Comment by valexopoulos** [comment]
After investigation with the help of @imousmoutis, the issue was related with the H2 database. For oracle and mysql/mariadb there is no problem when scheduling a job.
